### PR TITLE
Initial Setup of Bluetooth Integration

### PR DESCRIPTION
**Pull request by carterpeel**
I plan to add a server struct & corresponding methods later on. 

**EDIT:** I forgot to include the example code initally:

**[Test Code](https://github.com/carterpeel/ledfx_rewrite/blob/Bluetooth/integrations/bluetooth/btclient_test.go):**
```go
package bluetooth

import (
	"github.com/sirupsen/logrus"
	"testing"
	"time"
)

func TestNewClient(t *testing.T) {
	// Initialize a Bluetooth client adapter
	client, err := NewClient(logrus.DebugLevel)
	if err != nil {
		t.Fatalf("Error generating new BLE client: %v\n", err)
	}

	// Search through the device cache and discovery events for
	// a bluetooth device
	if err := client.SearchAndConnect(SearchTargetConfig{
		DeviceRegex:          `(?i)k850$`, // Case-insensitive, searches for "k850" ([AV] Samsung Sound Bar K850)
		ConnectRetryCoolDown: 2 * time.Second,
	}); err != nil {
		t.Fatalf("Error searching and connecting for BLE device: %v\n", err)
	}

	// Wait until a device is successfully connected
	client.WaitConnect()
}
```

**Output:** 
```bash
pi@hyperkit:~/ledfx_rewrite/integrations/bluetooth $ go test -v
=== RUN   TestNewClient
DEBU[0000] Default Bluetooth adapter: hyperkit
DEBU[0000] Powered on Bluetooth adapter...
INFO[0000] Starting tryCacheConnect...
INFO[0000] Found requested device in cache: (addr=5C:49:7D:96:36:11, name=[AV] Samsung Soundbar K850)
INFO[0000] Attempting to connect to "5C:49:7D:96:36:11" indefinitely...
INFO[0003] Connection to Bluetooth device with address "[AV] Samsung Soundbar K850" succeeded
--- PASS: TestNewClient (3.10s)
PASS
ok  	ledfx/integrations/bluetooth	3.106s
```

### CODE REVIEW

**Comment by shauneccles** [comment]
Now, I'm probably a bit dumb, what are we proposing to do with this integration?

**Comment by carterpeel** [comment]
> Now, I'm probably a bit dumb, what are we proposing to do with this integration?

Not a lack of intelligence on your part. It is my own responsibility to make that clear and I failed to do so, lol. 

I'm suggesting that LedFX handle the routing of audio seamlessly. For example, if you run LedFX on a Raspberry Pi, but want LedFX to process audio from your iPhone via AirPlay/Bluetooth, and you also want it to playback on your AirPlay/Bluetooth capable soundbar, LedFX should be able to do that. 

As most know, properly setting up PulseAudio/Bluetooth/etc. is quite a task. (especially for beginners)

In my eyes, this would be a huge QoL milestone for the software... Then we can ship the whole thing as a Docker container. (or ship prebuilt Pi images!)

**Comment by shauneccles** [comment]
I mean, if we can be OS/Hardware agnostic and handle everything, then yeah that's huge and we should deffo aim for that.

Is that the sort of end-goal you're envisaging?

I'm just not sure if this is going to turn into a pandoras box of troubleshooting etc if it doesn't "just work" - the python version is very specific in that it can only do what your OS can do. That kind of nips troubleshooting in the bud since if your OS doesn't present an audio device we can't do anything and they need to fix that.

Dunno. I like the idea. In it goes, if it's a terrible idea we can always reassess.

How will we CI the test, is the only question.

**Comment by carterpeel** [comment]
> I mean, if we can be OS/Hardware agnostic and handle everything, then yeah that's huge and we should deffo aim for that.
> 
> Is that the sort of end-goal you're envisaging?
> 
> I'm just not sure if this is going to turn into a pandoras box of troubleshooting etc if it doesn't "just work" - the python version is very specific in that it can only do what your OS can do. That kind of nips troubleshooting in the bud since if your OS doesn't present an audio device we can't do anything and they need to fix that.
> 
> Dunno. I like the idea. If it's a terrible idea we can always reassess once it's in.
> 
> Only question, how will we CI the test? (thank you for writing a test)

Sure thing. I think these integrations should be fully optional and not enabled by default (to prevent a troubleshooting nightmare later down the line)

CI would be difficult for these tests. I can try to whip up a docker-compose file that can emulate sound devices. I think that's possible. Maybe.

**Pull request merged**
