### PR TITLE
refactor udp and add tests

### PR DESCRIPTION
**Pull request by JBaczuk**

### CODE REVIEW

**Comment by shauneccles** [comment]
This has conflicts now :(

Did we want to refactor this or is this PR redundant?

**Comment by JBaczuk** [comment]
> This has conflicts now :(
> 
> Did we want to refactor this or is this PR redundant?

Should still be relevant, I'll go through and fix the conflicts.

**Comment by JBaczuk** [comment]
@shauneccles i went through and fixed the conflicts

**Comment by not-matt** [comment]
Used this to finish the UDP implementation, thank you @JBaczuk

**Pull request closed without merging**
